### ISSUE TITLE
Confusing rubygems instructions

### ISSUE THREAD

**Issue by moritzheiber** [tobyclemson/ruby_terraform#5]
It says in the documentation that you ought to install `ruby_terraform`. However, on rubygems.org there are two different versions available of this gem as far as I can see, `ruby_terraform` and `ruby-terraform`, with only the latter carrying the latest releases.

This should probably be reflected in the documentation and/or the two gems consolidated into a single release object.

**Comment by tobyclemson** [comment]
Hi Moritz,

Sorry, this is a relic from when I first released the library. It turns out ruby_terraform was already taken by another user so I had to publish as ruby-terraform.

I've updated the documentation to reflect this. If you're happy with the docs, I'll close this issue.

Thanks,
Toby

**Comment by moritzheiber** [comment]
No worries, I just meant to point this out, the documentation looks fine now! :+1:
